// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // The Prisma CLI requires a direct connection to the database to perform migrations.
    // Therefore, we use the DIRECT_URL (port 5432) here instead of the pooler url.
    url: process.env["DIRECT_URL"]!,
  },
});
